// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5YIjU9sFqXOTM0YweSuLoNjOQQleL4Tc',
    appId: '1:147251072467:web:8e86e13908402220e07326',
    messagingSenderId: '147251072467',
    projectId: 'moodle-3af4f',
    authDomain: 'moodle-3af4f.firebaseapp.com',
    storageBucket: 'moodle-3af4f.appspot.com',
    measurementId: 'G-PF33B36X9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNnjHFrkSjg-imppn-_HZVir5kgkz4DY',
    appId: '1:147251072467:android:832c5c332af67e85e07326',
    messagingSenderId: '147251072467',
    projectId: 'moodle-3af4f',
    storageBucket: 'moodle-3af4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2FEZyPdcCCfiYm9WbPFTS9xGY8j5tLw',
    appId: '1:147251072467:ios:f54b75e4c1188e52e07326',
    messagingSenderId: '147251072467',
    projectId: 'moodle-3af4f',
    storageBucket: 'moodle-3af4f.appspot.com',
    iosBundleId: 'com.example.moodle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2FEZyPdcCCfiYm9WbPFTS9xGY8j5tLw',
    appId: '1:147251072467:ios:f54b75e4c1188e52e07326',
    messagingSenderId: '147251072467',
    projectId: 'moodle-3af4f',
    storageBucket: 'moodle-3af4f.appspot.com',
    iosBundleId: 'com.example.moodle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5YIjU9sFqXOTM0YweSuLoNjOQQleL4Tc',
    appId: '1:147251072467:web:2d137ed06a8a0332e07326',
    messagingSenderId: '147251072467',
    projectId: 'moodle-3af4f',
    authDomain: 'moodle-3af4f.firebaseapp.com',
    storageBucket: 'moodle-3af4f.appspot.com',
    measurementId: 'G-8R816ZPD7P',
  );
}
